"""
This file is to read the results generated by `templates.py`
"""
import pickle
from typing import Dict, Tuple, List


def read_results(results_pickle: str):
    with open(results_pickle, 'rb') as f_results_pickle:
        results: Dict[str, Dict[Tuple, List[Tuple[Tuple, float, float]]]] = pickle.load(f_results_pickle)
    return results


def filter_cracked(results: Dict[str, Dict[Tuple, List[Tuple[Tuple, float, float]]]], guess_number_upperbound: int):
    filtered = {}
    for cls_name, templates_passwords in results.items():
        filtered_templates = {}
        for template, passwords in templates_passwords.items():
            filtered_passwords = []
            for pwd, ml2p, rank in passwords:
                if rank <= guess_number_upperbound:
                    filtered_passwords.append(("".join(pwd), ml2p, rank))
                else:
                    print(f"hello, {pwd}")
            if len(filtered_passwords) > 0:
                filtered_templates["".join(template)] = filtered_passwords
            pass
        if len(filtered_templates) > 0:
            filtered[cls_name] = filtered_templates
        pass
    return filtered


def wrapper():
    results_pickle = '/disk/cw/datasets/templates4neopets/rockyou1m_results.pickle'
    guess_number_upperbound = 10**120
    results = read_results(results_pickle=results_pickle)
    filtered = filter_cracked(results=results, guess_number_upperbound=guess_number_upperbound)
    print(filtered)
    pass


if __name__ == '__main__':
    wrapper()
    pass